# LangGraph LongMemEval Benchmarker Test Configuration

# Dataset configuration - using minimal test sample
longmemeval_repo_path = "./test"  # Use local test directory instead of external repo
dataset_variant = "longmemeval_minimal.json"  # Test with just 1 question, 2 sessions, 8 turns total

# MCP configuration  
mcp_url = "http://localhost:11546/mcp"
mcp_transport = "streamable_http"

# Model configuration - unified on AWS Bedrock
memory_agent_model = "anthropic.claude-3-haiku-20240307-v1:0"
qa_agent_model = "anthropic.claude-3-haiku-20240307-v1:0"  
evaluation_model = "anthropic.claude-3-haiku-20240307-v1:0"

# AWS Bedrock configuration
aws_region = "us-west-2"
# aws_access_key_id = "your_access_key"
# aws_secret_access_key = "your_secret_key"

# Benchmark configuration
vault_name = "longmemeval-test"
output_dir = "./test_results"
max_concurrent_conversations = 1
enable_debug_logging = true