name: mycelian-memory-service

services:
  memory-service:
    build:
      context: ../../server
      dockerfile: cmd/memory-service/Dockerfile
    container_name: memory-service
    ports:
      - "8080:8080"
    environment:
      - MEMORY_BACKEND_ENVIRONMENT=development
      - MEMORY_BACKEND_HTTP_PORT=8080
      - MEMORY_BACKEND_WAVIATE_URL=weaviate:8080
      - MEMORY_BACKEND_DB_DRIVER=sqlite
      - MEMORY_BACKEND_BUILD_TARGET=local
      - MEMORY_BACKEND_SQLITE_PATH=/root/.synapse-memory/memory.db
    networks:
      - memory-network
    restart: unless-stopped
    depends_on:
      indexer:
        condition: service_started
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - memory-sqlite-data:/root/.synapse-memory

  weaviate:
    container_name: weaviate
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.2
    platform: linux/arm64
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/v1/meta || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      QUERY_DEFAULTS_LIMIT: "20"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: "none"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
    networks:
      - memory-network
    restart: unless-stopped

  indexer:
    container_name: indexer
    build:
      context: ../../server
      dockerfile: cmd/indexer-prototype/Dockerfile
    environment:
      - DB_DRIVER=sqlite
      - SQLITE_PATH=/root/.synapse-memory/memory.db
      - WAVIATE_URL=weaviate:8080
      - OLLAMA_URL=http://host.docker.internal:11434
      - INDEX_INTERVAL=1s
    networks:
      - memory-network
    volumes:
      - memory-sqlite-data:/root/.synapse-memory
    depends_on:
      weaviate:
        condition: service_healthy

  # One-off container to bootstrap a deterministic local user for development
  user-bootstrap:
    container_name: user-bootstrap
    build:
      context: ../../server
      dockerfile: cmd/memoryctl/Dockerfile
    depends_on:
      memory-service:
        condition: service_started
    networks:
      - memory-network
    restart: "no"
    command: >
      sh -c "
        until curl -s http://memory-service:8080/api/health | grep 'UP'; do
          echo 'waiting for memory-service...';
          sleep 2;
        done;
        ./memoryctl users create --userId local_user --email dev@localhost --name 'Local User' --api http://memory-service:8080 || true
      "

networks:
  memory-network:
    driver: bridge
    name: synapse-memory-network 

volumes:
  memory-sqlite-data: 