# .golangci.yml  ── validated against GolangCI-Lint v1 schema
version: "1"                # ← MUST be a **string**, therefore quoted

run:
  tests: true               # true = lint test files, false = skip globally

linters-settings:           # top-level key (same indent as run:)
  errcheck:
    exclude-files:          # regex; errcheck will skip any file that matches
      - _test\.go$

issues:                     # top-level
  exclude-rules:            # lives *inside* issues:
    - path: _test\.go$      # regex for paths to silence
      linters:
        - errcheck