dataset_file_path = "/Users/deesam/workspace/mycelian/mycelian-memory/tools/longmemeval-benchmarker/out/longmemeval_5s.json"
vault_title = "longmemeval-quick"

[provider]
type = "bedrock"

[provider.bedrock]
region = "us-west-2"

[models]
agent = "anthropic.claude-3-5-haiku-20241022-v1:0"
qa    = "anthropic.claude-3-5-haiku-20241022-v1:0"
eval  = "anthropic.claude-3-5-haiku-20241022-v1:0"

[params]
top_k = 10
max_tool_calls_per_turn = 5
question_limit = 1
workers = 1
max_sessions_per_question = 2
max_turns_per_session = 0
# Limit sessions for quick behavior check
debug = true

memory_title_template = "{question_id}__{run_id}"

